"""empty message

Revision ID: 4c095e843b01
Revises: ff70d9751dbd
Create Date: 2017-06-28 18:07:42.171765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c095e843b01'
down_revision = 'ff70d9751dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('server_timezone', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'server_timezone')
    # ### end Alembic commands ###
