"""empty message

Revision ID: 94c3aead6f85
Revises: 505080799071
Create Date: 2017-06-27 12:26:09.941023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c3aead6f85'
down_revision = '505080799071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_telegram_chat_id'), 'user', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_telegram_chat_id'), table_name='user')
    # ### end Alembic commands ###
