"""empty message

Revision ID: ff70d9751dbd
Revises: 94c3aead6f85
Create Date: 2017-06-27 19:08:14.322872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff70d9751dbd'
down_revision = '94c3aead6f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('busy_until', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('session_dump', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'session_dump')
    op.drop_column('account', 'busy_until')
    # ### end Alembic commands ###
